name = "joularcoregui"
product-name = "Joular Core GUI"
identifier = "org.noureddine.joular.joularcore.gui"
version = "0.1.0"
out-dir = "./dist"

binariesDir = "target/release"

before-packaging-command = "cargo build --release"

binaries = [
  { path = "joularcoregui", main = true }
]

formats = ["all"]
